### ISSUE TITLE
Remove make.names() ?

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/googleAnalyticsR#101]
See https://github.com/MarkEdmondson1234/googleAnalyticsR/issues/100

May cause more issues than it solves.

**Comment by j450h1** [comment]
Is the goal to use a different strategy to have the column name not start with a number? How do you figure it causes more issues?

**Comment by MarkEdmondson1234** [comment]
Hi @j450h1 !  After a conversation on twitter it seems `make.names` makes some assumptions that breaks data.frames sometimes, and the above is one example.  So I'd prefer to have a custom function that we know exactly will do and raise an error if something goes amiss.  The issue is the API returns column names that are not respected by R data.frames sometimes. 

It could just be a small utility function that does the fix there (
`safe_names <- gsub("^X([[:digit:]]+)","\\1",safe_names)`) and then use that in the code.  A small change hopefully so I thought a quick win for #hacktober :)

**Comment by j450h1** [comment]
Hi Mark! Okay makes sense. I can try to tackle it.

**Comment by j450h1** [comment]
Do you have an example of a column name (dimension or metric) that R data.frames won't accept? I reviewed the list of all of them and the only ones that seemed problematic were the ones that started with digits. I don't think a safe_names function is necessary. Also on my computer, I have no problem with data frame columns starting with a digit. Perhaps there is an issue with older versions of R or older packages? Forgive me, if this is something obvious since I'm relatively new to making contributions on Github.

**Comment by MarkEdmondson1234** [comment]
Fair enough, it could just be the ones that come back with a number, in which case just removing make.names is easiest.  Best code is no code, as they say :)

**Comment by j450h1** [comment]
Sounds good. Now I just have to figure out why I'm getting Travis CI Build errors with my latest PR.

**Comment by MarkEdmondson1234** [comment]
If they fail due to the tests don't worry about it, I have to run those locally at the moment as the auth token on travis is expired.

**Comment by j450h1** [comment]
FYI.  I've been doing some testing and the 1st character of a column not being a digit seems to be only when you instantiate a data frame as such.

<br/>

    df <- data.frame(`7dayUsers`= c("test"))
    df
    #>   X7dayUsers
    #> 1       test
    colnames(df) <- c("7dayUsers")
    df
    #>   7dayUsers
    #> 1      test
