### ISSUE TITLE
Use googleAnalyticsR with Power BI

### ISSUE THREAD

**Issue by Kaelin1234** [MarkEdmondson1234/googleAnalyticsR#102]
Has anyone been able to successfully use googleAnalyticsR with Power BI? 

Thanks in advance!

**Comment by MarkEdmondson1234** [comment]
Its not on the supported R packages list for PowerBI, so it can't be called from within PowerBI.  I don't think a request will help either as they say no packages that call APIs can be used.

At work, we do use it for downloading data into BigQuery (via [bigQueryR](http://code.markedmondson.me/bigQueryR/)), then connecting powerBI to BigQuery.  That is a lot smoother now they have released a new driver for it. 

I'll close this issue though since there is not a lot I can do for this :)
