### ISSUE TITLE
How to pull non-sampled data with GA 360?

### ISSUE THREAD

**Issue by S-UP** [MarkEdmondson1234/googleAnalyticsR#103]
This may be a rather simple question but I am kind of unsure how I can pull non-sampled data when having access to Google Analytics 360.

Can I keep working with the v4 specification and set anti_sample==T, or do I have to migrate the code to the BigQuery way of pulling data?

Thanks for the info!

**Comment by MarkEdmondson1234** [comment]
Hi @S-UP - it depends :)

GA360 has higher sampling limits ([see here](https://support.google.com/analytics/answer/2637192?hl=en) ) so you could just query normally (with `anti_sample` off) and are less likely to get sampling.

Its preferable to query without `anti_sample` if you can since it breaks up API calls and distorts some metrics.

If it does sample, you still may be able to avoid it with a normal API call by setting up [Custom Tables](https://support.google.com/analytics/answer/2774517?hl=en) - query the exact same dimensions/metrics as you set up there and you should have even higher sampling limits.

Otherwise, you can use `anti_sample` and it will do the breakup of calls, but you will need less of them than a normal GA account.

But my preferred way is to use the BigQuery exports, either via `google_analytics_bq` or otherwise.

**Comment by S-UP** [comment]
Thanks for the quick walk-through of all options. I'll investigate what is most suitable for my current environment.

Best wishes!
