### ISSUE TITLE
Pivot queries seem to truncate one column of the pivot

### ISSUE THREAD

**Issue by gilliganondata** [MarkEdmondson1234/googleAnalyticsR#107]
_I don't honestly understand why anyone would ever pull pivoted data directly through the API when it's so easy to pull tidy data and then spread it with dplyr as necessary, but, nevertheless, this appears to be a possible bug, so I'm reporting it._

The issue is that pivoted values seem to come in missing one column. I've only tried this in scenarios where there is no filtering of the pivoted columns, as just a few values will come back -- **deviceCategory** and **userType**, for instance.

Code example:

```
my_pivot_object <- pivot_ga4("deviceCategory",
                             metrics = "sessions")

ga_data <- google_analytics_4(viewId = view_id,
                              date_range = c(start_date, end_date),
                              metrics = "sessions",
                              dimensions = "medium",
                              pivots = list(my_pivot_object),
                              anti_sample = TRUE)
```
The result, of `names(ga_data)` is then:

`[1] "medium"                         "sessions"                       "deviceCategory.mobile.sessions"
[4] "deviceCategory.tablet.sessions"`

There _should_ be a `deviceCategory.desktop.sessions` value.

**Comment by MarkEdmondson1234** [comment]
This actually looks like its an API bug, as the raw response only returns 2 rather than 3 pivots (Tablet, mobile, not desktop)

https://developers.google.com/apis-explorer/#p/analyticsreporting/v4/analyticsreporting.reports.batchGet?_h=1&resource=%257B%2522reportRequests%2522%253A%255B%257B%2522viewId%2522%253A%2522ga%253A81416156%2522%252C%2522dateRanges%2522%253A%255B%257B%2522startDate%2522%253A%25222017-08-25%2522%252C%2522endDate%2522%253A%25222017-09-24%2522%257D%255D%252C%2522samplingLevel%2522%253A%2522DEFAULT%2522%252C%2522dimensions%2522%253A%255B%257B%2522name%2522%253A%2522ga%253Amedium%2522%257D%255D%252C%2522metrics%2522%253A%255B%257B%2522expression%2522%253A%2522ga%253Asessions%2522%252C%2522alias%2522%253A%2522sessions%2522%252C%2522formattingType%2522%253A%2522METRIC_TYPE_UNSPECIFIED%2522%257D%255D%252C%2522pivots%2522%253A%255B%257B%2522dimensions%2522%253A%255B%257B%2522name%2522%253A%2522ga%253AdeviceCategory%2522%257D%255D%252C%2522metrics%2522%253A%255B%257B%2522expression%2522%253A%2522ga%253Asessions%2522%252C%2522alias%2522%253A%2522sessions%2522%252C%2522formattingType%2522%253A%2522METRIC_TYPE_UNSPECIFIED%2522%257D%255D%252C%2522startGroup%2522%253A1%252C%2522maxGroupCount%2522%253A5%257D%255D%252C%2522pageToken%2522%253A%25220%2522%252C%2522pageSize%2522%253A1000%252C%2522includeEmptyRows%2522%253Atrue%257D%255D%257D+&

**Comment by gilliganondata** [comment]
Indeed. It is! I'd wondered if that might be the case, but I just tried with the query you sent and one of my view IDs and saw the same thing. The column with the total keeps throwing me as it is, so I'm wondering if there is something in the GA code that also forgot about that column and, as a result, comes up one column short.

So -- definitely a GA v4 bug rather than a googleAnalyticsR bug.

**Comment by MarkEdmondson1234** [comment]
I've filed a bug report with them.

**Comment by MarkEdmondson1234** [comment]
It was technically possible to get the correct result before, but the default was confusingly set at 1 and not zero

```r
my_pivot_object <- pivot_ga4("deviceCategory",
                             metrics = "sessions", startGroup = 0)

ga_data <- google_analytics_4(viewId = view_id,
                              date_range = c(start_date, end_date),
                              metrics = "sessions",
                              dimensions = "medium",
                              pivots = list(my_pivot_object),
                              anti_sample = TRUE)
```

This next commit fixes that so by default it will get the first 6 columns (including the first)

**Comment by gilliganondata** [comment]
Heh-heh. Well, I'd still find myself 100% of the time doing the pivoting after the fact with dplyr, anyway.

**Comment by MarkEdmondson1234** [comment]
Yeah, thats best, but I guess its nice to have the option
