### ISSUE TITLE
gar_batch_walk not split path to URL

### ISSUE THREAD

**Issue by mrykinpavel** [MarkEdmondson1234/googleAnalyticsR#175]
## What goes wrong
I use gar_batch_walk to get result for 30 webproperties, but link for get date not change

## Steps to reproduce the problem
My code:
```
getAccountInfo <- googleAuthR::gar_api_generator(
  "https://www.googleapis.com/analytics/v3/management/",
  "GET",
  customConfig = list(httr::add_headers(c(
                                         "Content-type" = "multipart/mixed",
                                        "Accept-Encoding" = "gzip",
                                        "User-Agent" = "RStudio (gzip)")
                                                        )
                                  )
)

walkData <- function(){
     batch_headers <- function(batch_data){
              httr::add_headers(c(
                            "Content-type" = "application/http",
                            "Content-ID" = "",
                            "Accept-Encoding" = "gzip",
                            "User-Agent" = "RStudio (gzip)")
  )
  batch_data
}
walked_data <- googleAuthR::gar_batch_walk(getAccountInfo, listAccounts$accountId,
                                           path_walk = c("accounts", "webPropertyId"),
                                           gar_paths = list(accounts = listAccounts$accountId,
                                                           webPropertyId = listAccounts$webPropertyId
                                           ),
               batch_size = 1, batch_function = batch_headers, data_frame_output = FALSE)
walked_data
}
```

listAccounts - is data.frame with info about accounts

## Actual output
For each request link is GET /analytics/v3/management/ without arguments

Must be
GET /analytics/v3/management/accounts/XXX/webPropertyId/XXX

Maybe I'm not correct using argument path_walk and gar_paths, but I try any variant and founded all informaition about this function in google - I'm not understand how to use it.

Before you run your code, please run:
verbose 2:
2018-05-24 01:20:44> Batch API limited to [1] calls at once.
Request #: 102150771
2018-05-24 01:20:44> Skipping token checks as using cache
2018-05-24 01:20:44> Constructing batch request URL for: /analytics/v3/management/
2018-05-24 01:20:44> Making new batched cache
2018-05-24 01:20:44> Making Batch API call
2018-05-24 01:20:45> Forgetting cache
Error: lexical error: invalid char in json text.
                                       Not Found
                     (right here) ------^
In addition: Warning message:
 Show Traceback
 
 Rerun with Debug
 Error: lexical error: invalid char in json text.
                                       Not Found
                     (right here) ------^ 

verbose 0:
2018-05-24 01:18:01> Batch API limited to [2] calls at once.
Request #: 102150771 : 102160839
2018-05-24 01:18:01> Skipping token checks as using cache
2018-05-24 01:18:01> Skipping token checks as using cache
2018-05-24 01:18:01> Constructing batch request URL for: /analytics/v3/management/
2018-05-24 01:18:01> Constructing batch request URL for: /analytics/v3/management/
2018-05-24 01:18:01> Making new batched cache
2018-05-24 01:18:01> Making Batch API call
2018-05-24 01:18:03> Request Status Code: 400
Error : lexical error: invalid char in json text.
                                       <HTML> <HEAD> <TITLE>Bad Reques
                     (right here) ------^

2018-05-24 01:18:03> API returned error: Could not fetch response
2018-05-24 01:18:03> No retry attempted: Could not fetch response
2018-05-24 01:18:03> Forgetting cache
Error in if (s[length(s)] == "") s <- s[-length(s)] : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: No JSON content found in request 
2: Error in batch cache function 
3: In split_vector(r, index) : No index found
4: In split_vector(x, index, remove_splits = FALSE) : No index found
5: In split_vector(x, index, remove_splits = FALSE) : No index found
6: In split_vector(x, index, remove_splits = FALSE) :
 Show Traceback
 
 Rerun with Debug
 Error in if (s[length(s)] == "") s <- s[-length(s)] : 
  missing value where TRUE/FALSE needed

## Session Info
R version 3.4.4 (2018-03-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Russian_Russia.1251  LC_CTYPE=Russian_Russia.1251    LC_MONETARY=Russian_Russia.1251
[4] LC_NUMERIC=C                    LC_TIME=Russian_Russia.1251    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] googleAuthR_0.6.2.9000 bindrcpp_0.2           googleAnalyticsR_0.4.2 RGA_0.4.3             

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.15        bindr_0.1           knitr_1.19          xml2_1.2.0          magrittr_1.5       
 [6] devtools_1.13.5     tidyselect_0.2.4    ryandexdirect_2.5.0 R6_2.2.2            rlang_0.2.0        
[11] dplyr_0.7.4         stringr_1.3.0       httr_1.3.1          plyr_1.8.4          tools_3.4.4        
[16] git2r_0.21.0        withr_2.1.1         assertthat_0.2.0    openssl_1.0.1       yaml_2.1.17        
[21] digest_0.6.15       tibble_1.4.2        tidyr_0.8.0         purrr_0.2.4         bitops_1.0-6       
[26] RCurl_1.95-4.10     curl_3.1            glue_1.2.0          memoise_1.1.0       stringi_1.1.6      
[31] pillar_1.2.1        compiler_3.4.4      jsonlite_1.5        lubridate_1.7.4     httpuv_1.3.6.2     
[36] pkgconfig_2.0.1    

For developers:
https://developers.google.com/analytics/devguides/config/mgmt/v3/mgmtReference/management/webproperties/get

**Comment by MarkEdmondson1234** [comment]
I don’t think management API functions are supported by the batch, but aside that may I check you are aware of the function ‘ga_account_summary()’ in ‘googleAnalyticsR’ that looks to return the data this function would do. 

Otherwise if you are looking to keep this low level for educational or other purposes, I suggest using the library ‘future.apply’ to launch a normal API call in parallel R sessions. Bear in mind the API will have quota limits to respect.

**Comment by mrykinpavel** [comment]
Thanks for your answer, @MarkEdmondson1234!

Link for batch managment API:
https://developers.google.com/analytics/devguides/config/mgmt/v3/batching

Managment API have low limits to change (50 request  for day), and this why google advise batching.

Thanks for info about future.apply!

**Comment by mrykinpavel** [comment]
@MarkEdmondson1234 do you have any idea about it?

**Comment by MarkEdmondson1234** [comment]
My mistake on management API not supporting batch.

May I just check what result you are looking for, as it looks like `googleanalyticsR::ga_account_summary()` would give you what you need in quick time:

```r
library(googleAnalyticsR)
system.time(ga_account_list())
   user  system elapsed 
  0.141   0.001   0.335 
```

Even if getting the full web property object, 30 calls will be quick - I have 34 web properties in this call that is 35 API calls:

```r
library(googleAnalyticsR)
system.time(lapply(ga_account_list()$accountId, ga_webproperty_list))
   user  system elapsed 
  0.409   0.016  12.978
```

However, if you want to do it from the bottom, I would make these changes:

* You don't need to add your `customConfig` block in `getAccountInfo` as these are set for batching already - for instance the boundary condition was overwritten. 
* Similarly, the `batch_headers()` function is overriding settings that are already set for batching
* `path_walk`needs to be the values of the arguments to walk over, so if walking over id=1, id=2, etc. then it would be `path_walk="id", walk_vector=c(1,2,3,4,etc.)`
* `gar_path`is intended for other arguments to the function `f` you may need to pass through.
* `gar_batch_walk()` only supports changing one value at a time, for perhaps multiple arguments (I think only the start-date, end-date being the only example you  would use more than 1
* `batch_size`should be over 1 for batching to be of any benefit at all
* The `f` function needs to be a `gar_api_generator()` function that uses `path_args`(or pars_args, body args if needed) to construct the URL (rather than say using `sprintf`) 
* the `batch_function` operates on the parsed output of each call

All that said this is a working example, that gets the data in 1.7 seconds in two API calls, but I still think the `ga_account_list()` is probably what you need. 


```r
getAccountInfo <- googleAuthR::gar_api_generator(
  "https://www.googleapis.com/analytics/v3/management/accounts",
  "GET", data_parse_function = function(x) unique(x$items$id))

getWebpropertyInfo <- googleAuthR::gar_api_generator(
  "https://www.googleapis.com/analytics/v3/management/", # don't use sprintf to construct this
  "GET",
  path_args = list(accounts = "default", webproperties = ""),
  data_parse_function = function(x) x$items)

walkData <- function(){

  # here due to R lazy evaluation  
  accs <- getAccountInfo()
  


  googleAuthR::gar_batch_walk(getWebpropertyInfo, 
                              walk_vector = accs,
                              gar_paths = list("webproperties" = ""),
                              path_walk = "accounts",
                              batch_size = 100, data_frame_output = FALSE)
}

walkData()
```

I admit it probably needs some better documentation :)  this question will help that, thank you.

**Comment by MarkEdmondson1234** [comment]
The googleAuthR docs on batching have been updated with this example, thanks

http://code.markedmondson.me/googleAuthR/articles/advanced-building.html#walking-through-batch-requests

**Comment by mrykinpavel** [comment]
@MarkEdmondson1234 my goal is change settings for webProperties:
https://developers.google.com/analytics/devguides/config/mgmt/v3/mgmtReference/management/webproperties/update

Example:
PUT https://www.googleapis.com/analytics/v3/management/accounts/**accountId**/webproperties/**webPropertyId**

I want to change dataRetentionTtl for all webProperties to INDEFINITE.

If I understand, I can't walk for two id's (accountId and webPropertyId), I'm right?

**Comment by MarkEdmondson1234** [comment]
Ah I see, cool then just adapt the example with `PUT` and `body_walk`

You can't walk two IDs, but you will be able to batch all web properties under an accountId.
