### ISSUE TITLE
Why google_analytics() defaults to 1000 maximum results?

### ISSUE THREAD

**Issue by j450h1** [MarkEdmondson1234/googleAnalyticsR#192]
Looks like if I want all results, I have to specify ```max = -1``` or else only 1000 records are returned and this message appears:

```
2018-08-29 12:45:45> Downloaded [1000] rows from a total of [16981].
```

Solution to get all results:
 
```
A  <- google_analytics(viewId = GA.VIEW.ID,
                         date_range = rep(GA.DATE, 2),
                         metrics = 'transactions',
                        dimensions = c('ga:date', 'transactionId'),
                       max = -1
)
```
This seems a bit unintuitive. Is there a good reason for that being the default? For beginners it could be even more confusing.

**Comment by MarkEdmondson1234** [comment]
It is on purpose, mainly since if it is set to all results (-1) a newbie could accidentally set off a long API call sequence, and so the default limit is set to a number low enough to see results quickly and sufficient for most quick fire queries (like how many sessions per device that would only have 3 rows).  The download rows message is there as a prompt to make sure its not unknown.  

It is the [first documentation on the website](http://code.markedmondson.me/googleAnalyticsR/v4.html#number_of_results) so I hope it isn't too confusing, but open to alternatives.

**Comment by j450h1** [comment]
I see your point. To be honest, I never reviewed that documentation and even initially overlooked that message about 1000 rows since I just expected the behaviour to return all records without specifying anything else (others might as well and then I was doing a join with another dataset and possibly wouldn't have even noticed until much later. Maybe there is a way to check how "large"/long (maybe a dry run option?) of any API call it is and provide warnings if a newbie exceeds what we define is a long API call. Not a big deal, just thinking of how most people could use it "dangerously" like I almost did.

**Comment by j450h1** [comment]
OR I could have just read the documentation, but I guess many people like me don't do it unless they encounter an error first...
