### ISSUE TITLE
Possible to release memory after google_analytics() call?

### ISSUE THREAD

**Issue by tkafka** [MarkEdmondson1234/googleAnalyticsR#216]
**Is your feature request related to a problem? Please describe.**
I am downloading GA data by days in a loop (for each day I call `google_analytics(...)`). I was expecting the memory usage to be constant, but it is increasing as the script loops over days. It seems that there is a lot of RAM that is not released.

**Describe the solution you'd like**
I understand that the script uses a lot of caching, but I'd like to ask if it was possible to add some `release_memory` command that would release whatever memory googleAnalyticsR is using behind the scenes, as I am sure at that moment that no data fetched with yesterday's GA data will be useful for fetch of a next day's data.

**Describe alternatives you've considered**
I tried calling this, but it doesn't seem to help much (it saved about 20 MB out of 1.3 GB as measuerd by `pryr`'s `mem_used()`):

    ga_data = google_analytics(...)
    # save ga_data to file
    rm(ga_data)
    gc()

**Additional context**
n/a

**Comment by MarkEdmondson1234** [comment]
I would advise setting the cache to a file instead, that way the RAM will only handle the current API call.  I assume you have a long running R session, as otherwise restarting R would clear it. 

That way it will increase disk space instead, and you get the advatage of caching if you repeat API calls.  There is a video explainer on the website http://code.markedmondson.me/googleAnalyticsR/articles/v4.html#customising-api-fetches

..but basically its just adding this call before your API calls:

```r
ga_cache_call("my_cache_folder")

## will make the call and save files to my_cache_folder
google_analytics(ga_id, 
                 date_range = c("2017-01-01", "2017-03-01"), 
                 metrics = "sessions", 
                 dimensions = "date",
                 max = -1)
```

Otherwise, if you are set on clearing cache, then you can call `googleAuthR::gar_cache_empty()` to reset it

**Comment by tkafka** [comment]
Yep, but I have no idea what is happening - I peeked into memoise::cache_memory, it saves data into session env, and theoretically Rstudio could save and reuse it across runs, but the .RData is only tens of kB large and it would need to contain > 1 GB of cached GA data in order to explain what I'm seeing.

https://github.com/r-lib/memoise/blob/master/R/cache_memory.R

Mysteries of life :).
