### ISSUE TITLE
multi_account_batching = TRUE does not refresh OAuth token

### ISSUE THREAD

**Issue by JimmyG3** [MarkEdmondson1234/googleAnalyticsR#25]
It looks like multi_account_batching does not refresh the OAuth token.  If I start an R session with a query where multi_account_batching = TRUE, I get an error.  If I run a standard google_analytics query, the console prints "Auto-refreshing stale OAuth token."  After that, I have no errors with multi_account_batching = TRUE.

**Comment by MarkEdmondson1234** [comment]
That is weird :)  Could you post some code from a fresh R session in the order it creates an error?  Its possible an option is set or not set where it shouldn't be.

**Comment by JimmyG3** [comment]
Here you go.  
`library(googleAnalyticsR)
library(googleAuthR)
library(dplyr)
library(lubridate)
load("./token_file")
options("googleAnalyticsR.client_id" = token$app$key)
options("googleAnalyticsR.client_secret" = token$app$secret)
options("googleAuthR.client_id" = token$app$key)
options("googleAuthR.client_secret" = token$app$secret)
gar_auth(token = token)
ga_auth(token = token)

gadata <- google_analytics(ga_views$ga_id, start = '2016-01-01', end = '2016-05-31',
	metrics = c('users', 'sessions', 'pageViews'),
	multi_account_batching = TRUE)
Fetching all ids at same time (max 10 per API call
Request #: ga:7647996 : ga:7648051 : ga:7652320 : ga:7652342 : ga:7652350 : ga:7652364 : ga:7674652 : ga:8971852 : ga:7652402 : ga:7674676
Request to profileId:  ()
Error in if (x$kind == "analytics#gaData") { : argument is of length zero
google_analytics(id = ga_views$ga_id[1:5], start = '2016-01-01', end = '2016-01-07',
	metrics = 'ga:pageViews',
	multi_account_batching = TRUE)
Fetching all ids at same time (max 10 per API call
Request to profileId:  ()
Error in if (x$kind == "analytics#gaData") { : argument is of length zero
google_analytics(id = ga_views$ga_id[1:5], start = '2016-01-01', end = '2016-01-07',
	metrics = 'ga:pageViews')
Auto-refreshing stale OAuth token.


gadata <- google_analytics(ga_views$ga_id, start = '2016-01-01', end = '2016-05-31',
	metrics = c('users', 'sessions', 'pageViews'),
	multi_account_batching = TRUE)
Fetching all ids at same time (max 10 per API call
It's succesful here. `

**Comment by MarkEdmondson1234** [comment]
Ok, this looks like an issue with how you store the token.  You don't need to pass in the token to `gar_auth()` if its in the same working directory, and you are passing an old token, so it only works the second time once its refreshed the token itself. 

Also the client ID and secret you can keep explicit in the script, as this won't change, and you really only need to set it and authenticate once for either `googleAnalyticsR`or `googleAuthR`(`googleAuthR` just copies it from `googleAnalyticsR`).  You really only need to worry about authenticating with gar_auth() if you are doing it for multiple APIs.

I have [updated the website about using auth here](http://code.markedmondson.me/googleAnalyticsR/setup.html) that may help give an overview. 

For your code then, I suggest the following changes should let it work first time every time:

```r
## make sure you always use same working directory, best way is to use RStudio projects. 
library(googleAnalyticsR)
library(dplyr)
library(lubridate)
options(googleAnalyticsR.client_id = "YOUR_CLIENT_ID")
options(googleAnalyticsR.client_secret = "YOUR_CLIENT_SECRET")
ga_auth()

gadata <- google_analytics(ga_views$ga_id, start = '2016-01-01', end = '2016-05-31',
    metrics = c('users', 'sessions', 'pageViews'),
    multi_account_batching = TRUE)

```
If you want to use a file to store all your credentials, then consider using `googleAuthR::gar_auth_service` instead of `ga_auth` and download the JSON file for service accounts and add the service email as a user to your GA account.  This is quicker auth as it doesn't need to refresh tokens.
