### ISSUE TITLE
Custom dimension default filter

### ISSUE THREAD

**Issue by Georgi-Petkov** [MarkEdmondson1234/googleAnalyticsR#285]
**Is your feature request related to a problem? Please describe
Hi Mark, I would like to thank you first for the GREAT job you've done with googleanalyticsR.
One thing has bothered me though while using the package and I'm pretty sure it's dictated by Google. I created a custom dimension which is a customer id that we provide to Google and when querying for it, it filters out all NULL values so I get only rows where customer id is available. I find this behaviour inappropriate, I believe the right way would be to get NA where values are not available.

**Describe the solution you'd like**
In my opinion, getting all raws with NAs where the value is missing would be better.

**Describe alternatives you've considered**

**Additional context**

**Comment by MarkEdmondson1234** [comment]
Yes there is not much we can do about this unfortunately. You can see the “allow
Empty rows” is always set to true at https://github.com/MarkEdmondson1234/googleAnalyticsR/blob/5a5f240a65d376b940b93e37f084c42835e37769/R/ga_v4_get.R#L202

If you want the behaviour you describe then you could try sending in an empty string “” rather than undefined when the row is empty in your JavaScript tags (eg Google tag manager) but the api response as far as I know can’t be modified.


________________________________

**Comment by Georgi-Petkov** [comment]
Thanks Mark, I will try out your suggestion with the empty string. I was wondering if I'm doing something wrong because in Google Analytics I can create a report and see how many logged-in vs not logged-in.
