### ISSUE TITLE
A question about the users metric

### ISSUE THREAD

**Issue by maelle** [MarkEdmondson1234/googleAnalyticsR#288]
First of all, thanks for a great package. I've a question about an output that I find surprising but that might be due to the API. Sorry in advance if that's the case.

I read that [Google Analytics added the users metric on 2016-09-01 for standard properties](https://support.google.com/analytics/answer/7667196?hl=en#data-retention-and-the-users-metric). 

Hence I do not expect getting any user before the 2016-09-01. What I did not expect was to get all 0's if the date range contains the 2016-08-22 (which I suppose is the date at which the users was added to the property I'm looking at). I.e.

```r
google_analytics(viewId = viewId, 
                 date_range = c("2016-08-23", "2016-09-15"), 
                 metrics = "users", 
                 dimensions = c("date"),
                 max = -1)
```

gives me actual numbers for all dates.

```r
google_analytics(viewId = viewId, 
                 date_range = c("2016-08-22", "2016-09-15"), 
                 metrics = "users", 
                 dimensions = c("date"),
                 max = -1)
```

gives me all 0's including for the dates for which I had users number with the first example. 

I tried digging a bit to find whether that was what the API returns, but I had trouble extracting the raw response, hence my asking.

**Comment by MarkEdmondson1234** [comment]
Hello and thanks for using the package. :)

Hmm well never heard of this before but I suspect it’s the response from the api. You can compare to using the JavaScript based query explorer to verify https://ga-dev-tools.appspot.com/query-explorer/

users as a metric in general is problematic since it’s really unique count of cookies, and those are not reliable or cater for the same user in mobile and desktop for example. They are also date range dependent as it’s a count of unique cookies in the time period you specify, so I guess that’s why if you go before the implementation date it sends 0 for all data.

If you can I would suggest using sessions instead as it’s more reliable.

You can inspect more api responses in R by using the googleAuthR.verbose option. Setting it to lower than the default 3 gives more feedback spam. If you set it to 0 it will write the entire request and response to an object in your working directory.

Hope that helps!


________________________________

**Comment by maelle** [comment]
Thank you, that helps a lot!!
