### ISSUE TITLE
Split a call and TryCath any API Error to continue to the next chunk

### ISSUE THREAD

**Issue by OmarGonD** [MarkEdmondson1234/googleAnalyticsR#303]
**Is your feature request related to a problem? Please describe.**

I'm working with a client that has a 360 GA account that is collecting a great amount of events and other hits. 

I've been task to report past years: 2019, 2018, 2017.  I want to download data from the API and make some analysis. However, the data is too much that I've ended splitting it and using a helper function to split the date range in n days.

Even with this trick, some API calls take for ever, and sometimes I get errors. 

**Describe the solution you'd like**

I'd like to inside my script capture any error in a TryCatch way, in order to:

1.- If API call fails continue to the next date range.
2.- Or if the API Call fails, split it even more the date range and try with these new data ranges (not altering the other ones that were already created.
3.- Split can also happen when API Calls take longer time than the median (20% longer?).

**IMPORTANT:** Every data returned should be write to a CSV file, to join them after all API Calls are made, otherwise the memory gets overflowed and you get Error: insufficient memory. Ideally the name of the CSV should contain start date and end date, to avoid confusions.

**Describe alternatives you've considered**

I've tried, apparently, all arguments and options of google_analytics() function and at the end, thanks to a video of Mark, I've ended using the make_dates helper function and apply function to loop and fetch the calls.

I'm not sure of other alternatives, but would love to hear if they exist.

**my code:**
```

library(googleAuthR)
library(googleAnalyticsR)
library(zoo)


viewID <- xxxxxxxx

som <- function(x) as.Date(as.yearmon(x))
eom <- function(x) as.Date(as.yearmon(x), frac = 1)

month_ranges <- function(from, to) {
  if (inherits(to, "yearmon")) to <- eom(to)
  s <- seq(som(from), eom(to), "month")
  data.frame(from = pmax(as.Date(from), s), to = pmin(as.Date(to), eom(s)))
}


my_dates <- month_ranges(som("2019-01-01"), eom("2019-12-31"))


my_fetch <- function(ga_id, d1, d2) {
  google_analytics(ga_id,
                   date_range = c(d1, d2),
                   metrics = c("totalEvents"),
                   dimensions = c("ga:date", "ga:eventCategory", "ga:eventAction", "ga:eventLabel"),
                   anti_sample = TRUE,
                   anti_sample_batches = 1,
                   rows_per_call = 400)
}


my_fetches_fetches <- mapply(my_fetch, viewID, my_dates$start, my_dates$end, SIMPLIFY = FALSE)


total <- do.call(rbind, my_fetches_fetches)


```

**Comment by MarkEdmondson1234** [comment]
How big is each data fetch in rows?  

You should not get any errors if you use `slow_fetch=TRUE` - it bypasses the hacks to speed up responses for normal interactive purposes on smaller data, but those hacks will generate 500 errors on large complicated queries.  Its those 500 errors and the subsequent retries that will be the main cause of delay in your queries.  This is my biggest recommendation out of all the other settings. 

Likewise you should not need to split the call into days if you specify `anti_sample_batches`.  The outside loop above doesn't help much since setting `anti_sample_batches = 1` effectively  means one API call per day anyway, so you gain nothing from looping over months.  

If you want to speed it up a bit, you can fetch up to 10 API calls at  a time so you can parrellise using `library(future)` or similar.  An example is on the website.

So all that put together I think you will get better or similar performance if you do this code:

```
library(googleAnalyticsR)
library(dplyr)
options(googleAuthR.verbose = 2)

ga_auth()

daily_walk <- google_analytics(ga_id,
                        date_range = c("2019-01-01", "2019-12-31"),
                       metrics = "totalEvents",
                       dimensions = c("date", "eventCategory", "eventAction", "eventLabel"),
                       anti_sample = TRUE,
                       slow_fetch = TRUE
                       anti_sample_batches = 1)
```

I think with slow_fetch=TRUE then the default 10000 rows per API call is fine, but you could modify that downwards with `rows_per_call` if you see it still generates 500 errors.  Specify `options(googleAuthR.verbose = 2)` to get more feedback on the API calls. 

If it is a lot of data then you will run out of RAM, R only uses RAM.

You could modify the above to use cached calls writing to disk, or save each year/month etc to an RDS file via `writeRDS(daily_walk, file="thismonth.rds")` or to CSV, but if it is a lot of data my recommendation would be to upload it to a database such as BigQuery so you can work with it easier.

**Comment by OmarGonD** [comment]
Thank you, Mark. 

The problem is the size of the resulting data.frame: 7,849,917 rows and 5 observations. As a CSV it weights more than 2GB.

Even making month by month calls I've got errors, and have lost hours because I've to make smaller calls, sometimes even making a query of a single day.

Also:

1.- I would still need to make a call using a for loop and `writeRDS(daily_walk, file="thismonth.rds")` for each successful code. However, I've seen that even calling a single month with `anti_sample_batches = 1` takes for ever and never returns the data.  In this cases, I've had to split the month call into days calls (2,3 or 5 days ranges) to get the data. 

2.- I think the code you show would also show: `Error enough memory, because of the size of the data to be downloaded`.

3.- In order to upload the data to BigQuery, first I need to downloaded it with R, right? Or Can I push the data directly to BigQuery? Is faster to access the data from BigQuery from R, than calling it from the API? 

Again, thank you for your time.

**Comment by MarkEdmondson1234** [comment]
If the above code pulls out more data than R can handle, then do not use `anti_sample_batches` or `anti_sample` which will gain you nothing and loop through the dates yourself, writing to file each loop.  You could also upload to BigQuery or work with the data afterwards using `data.table()` or other methods, but at least once the data is downloaded you can do what you need.

For a CSV of 8M rows for a year that should be around 22,000 rows per day which should have no issue in downloading.

```r
# make the dates to fetch
my_dates <- seq(as.Date("2019-01-01"), as.Date("2020-01-01"), by = 1)

my_fetch <- function(d){
  message("fetching API for date: ", d)
  o <- google_analytics(ga_id,
                        date_range = c(d, d),
                       metrics = "totalEvents",
                       dimensions = c("date", "eventCategory", "eventAction", "eventLabel"),
                       slow_fetch = TRUE)
  write_to <- paste0("myfile",d,".csv")
  write.csv(o, write_to)
  write_to
}

# parrelise this if you like via library(future)
my_downloads <- lapply(my_dates, my_fetch)

# then work with the list of csvs - for instance reading in again into one data.frame
df <- Reduce(rbind, lapply(my_downloads, read.csv))

# or upload to BigQuery
library(bigQueryR)
lapply(my_downloads, function(x) bqr_upload_data(upload_data = x))

# or something else

```

**Comment by OmarGonD** [comment]
Thank you, yes I think the problem is the size of the data returned. I'll need to download each day and rbind all csv files. 

The function `my_fetch` provided doesn't recieve an viewID, maybe this could be improved. Also, I'd recommend using do.call instead as Reduce, as Reduce consumes more memory when operating. 

See: https://stackoverflow.com/questions/37636463/how-to-use-reduce-function-in-r-parallel-computing
