### ISSUE TITLE
Error using google_analytics_account_list() 

### ISSUE THREAD

**Issue by ilyasustun** [MarkEdmondson1234/googleAnalyticsR#52]
Windows 10 64 bit.
R 3.3.2
RStudio Version 1.0.44

The code:
`account_list = google_analytics_account_list()`

returns the following error:

```
Error : df is not a data frame
API Data failed to parse.  Returning parsed from JSON content.
                    Use this to test against your data_parse_function.
```

How can it be solved?

**Comment by MarkEdmondson1234** [comment]
I've seen this before when the email authenticated under has no GA Views to list, or only one - could this be the case?

**Comment by ilyasustun** [comment]
Well I have one project yes, or one View. But why would one ga view give an error?

**Comment by MarkEdmondson1234** [comment]
R treats one row data.frames as vectors sometimes, but I've not had an account to test it upon with only one View.

Its recommended anyhow not to just have one, since ideally you should have a raw data profile then another with filters applied against bots etc.

But this also should not be a problem since a previous fix I did, so may I ask what version of the package you are using?  Typing the output of the below will give all the info needed:

```r
sessionInfo()
```

And also to see if the same problem persists if you install the development version:

Install devtools if you don't have it:

```r
install.packages(devtools)
```

Then install via Github:

```r
library(devtools)
install_github("MarkEdmondson1234/googleAnalyticsR")
```

Note also that you should still be getting data in the `account_list` object, just not in a data.frame, so if you still have a problem see if you can paste the output of `str(account_list)` then I can see if its a bug I can fix.

**Comment by MarkEdmondson1234** [comment]
As reported also here https://github.com/MarkEdmondson1234/googleAnalyticsR/issues/41

**Comment by MarkEdmondson1234** [comment]
@mischa2002k2 @ilyasustun I found the bug for parsing the account summary when its only one row, its fixed now for the version on github
